### ISSUE TITLE
[ FEATURE REQUEST ] Please Consider these

### ISSUE THREAD

**Issue by OshekharO** [mrepol742/PROJECT-WEBVIUM#1]
1. change default homepage to duckduckgo or startpage
2. add auto translate function like chrome
3. Change bottom toolbar style like EasyBrowser or Fulguris
4. add amoled theme
5. If possible add custom adblock filter list chooser

If all these are possible without removing existing features then please consider it.

**Comment by mrepol742** [comment]
Hello OshekharO,

- You can change the default home or startup to your preferred search engines by going to
   Settings > Search > Search Engines and Setting up the Homepage to Default by going to
   Settings > General Homepage > Choose Default.
- Auto translate will come soon as we change and improve the app tabs system
- Amoled Theme may come in the near future
- AdBlocker is still at its development and may received additional changes soon while the v2.8 is rolling out in dev.

**Comment by OshekharO** [comment]
![Screenshot_20220218-095319_Webvium Dev](https://user-images.githubusercontent.com/95137948/154617210-5dff39ad-4a9c-4b60-ac3f-b16e63525e79.png)

Tried changing homepage but still shows the pre-installed one.

And if possible bottom toolbar style like EasyBrowser or Fulguris or just increase the size of the toolbar it's way too small.

@mrepol742 thx for taking your precious time to listen to my requests.

And if you are going to add auto translate please consider integrated one instead of web one like ( kiwi browser ) but still kiwi browser is not able to translate pages automatically i have to click on translate again and again ( this issue doesn't exist in chrome ).

**Comment by mrepol742** [comment]
Hi OShekharO,

The requested changes will be implemented soon after adding required javascode and java code that will complete the Search Dev. and Webvium VPN bridge...

The app is currently closed source. Tho web side is open source. both of the Search & Search Dev site including the javascript are located in the github... as of now the search dev arent complete it may show only one background or nothing at all.

All web thing in webvium that does load without internet are all hardcoded to the app java files while the rest are all hosted in github publicly..

The dev one are updated on each new push to the repository every day so the app may failed at some cases tho i stil guaranteed its stable cuz i also uses it as my phone default browser.

**Comment by OshekharO** [comment]
@mrepol742 

Bro check this out: https://oshekharo.github.io/Webvium-Search/

Tried to make it as simplistic as possible without making it look ugly 🙂.

**Comment by mrepol742** [comment]
HI OshekharO,

I have check it out its so cool simple and minimalists. Webvium Search needed to support webvium feature primarily the Background API's. and Duckduckgo icon and name may be copyrighted.

As of now to contribute to webvium search development you can see its source codes in https:///github.com/mrepol742/mrepol742.github.io 

search for stable 
searchdev for dev

Having a good domain other than github io would be pretty cool. I have access to one year host with SSL in 2 domains but i havent redeem it yet i want to use it for the future when it really needs for now the search page will reside to the github. since i use github too much in the project.

To thanks you for creating this page awesome page ill add it on next update to the homepage options. But please make sure to remove or replace the duckduckgo name and icons for copyright reasons since this is beyond personally usage and more on commercial. 

Javascript function:
boolean : WebviumSearchSuggestion.isSearchSuggestionsEnabled() // returns weather the Suggestions is enabled
xml : WebviumSearchSuggestion.getResponse(var string); // returns the search suggestions

Look for WebviumSearchHelper for assist in validating inputs.

for ref:
https://github.com/mrepol742/mrepol742.github.io/blob/master/js/search.js

dev ref:
https://github.com/mrepol742/mrepol742.github.io/blob/master/js/searchdev.js

**Comment by OshekharO** [comment]
@mrepol742  

Ok bro will check other thing later and will replace duckduckgo logo with Webvium or some other which will not have any copyright protection 🤞

**Comment by mrepol742** [comment]
Hi OshekharO,

You can use replace it with un copyrighted names like as simple as Search. 

Other than that my friend tested the site and found an issue when the input is clicked and the software keyboard is up the input is nowhere to see.

and thanks for domain recommendations for hosting freely.. will check on it on free time.. 

I currently stop continuing the update till later its night here 6:54 philippines time . needed to prepare for dinner..

**Comment by OshekharO** [comment]
@mrepol742 

Ok will check with my laptop later if there exist such issue. ( No such iss was found while searching with my mobile )

**Comment by mrepol742** [comment]
Hi OshekharO,

https://user-images.githubusercontent.com/62317165/154800839-c1ccd009-d21e-41af-ae3b-e98428916989.mp4

Here is the screen video of the issue.

Without further do imma go back programming now.
