### ISSUE TITLE
Why not open source?

### ISSUE THREAD

**Issue by mindplay-dk** [mrepol742/PROJECT-WEBVIUM#2]
Just wondering, why isn't this open source anymore?

Perhaps more importantly, how can we trust a browser that isn't open source, and isn't even listed in the app store?

For all we know, this browser will sell our information and steal passwords or credit card numbers.

As a web developer and minimalist, I am definitely interested in seeing what a 500 KB browser can do on the modern web - I think it's wild that anyone would even attempt to build a browser in this day and age.

But how could anyone feel safe actually using this? 🤔

**Comment by mrepol742** [comment]
Hi
 it was listed on google play store by the dragon programming language creator but it cost a lot of issues because of newer updates was not getting push to the google play its been 3 times lower. Webvium is available in Amazon App Store, Uptodown Store, GetJar, samsung Galaxy store apart from this github and mysite... soon to be available at google..
it was closed source in a pull i conducted a year ago on facebook.

post:https://web.facebook.com/photo/?fbid=129242156143912&set=a.113425954392199
now it has one heart higher than the last time but the changes have already done.. 
Im doing my best to get a console account as soon as possible to be able to publish on google play without any delay....

here a screenshot of it before tho it was still cache no idea why but aavesh told me it was deleted.
![screenshot](https://user-images.githubusercontent.com/62317165/179215641-830db865-87cc-44a6-8565-85c24c94bb67.png
